# Generated by Django 2.1.2 on 2020-04-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_news_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
