# Generated by Django 2.1.2 on 2020-04-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
